FND/FND/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shabbat/', include('shabbat.urls'))
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FND/shabbat/urls.py
from django.urls import path

from . import views

app_name = 'shabbat'
urlpatterns = [
	path('english', views.index, name='index'),
	path('hebrew', views.index_hebrew, name='index_hebrew'),
	path('hello', views.hello, name='hello'),

]

FND/shabbat/models.py
from django.db import models
from django.contrib.auth.models import User

class GroupA(models.Model):
	organiser_name=models.CharField(max_length=100)
	name2=models.CharField(max_length=100)
	name3=models.CharField(max_length=100)
	name4=models.CharField(max_length=100)
	organiser_email=models.CharField(max_length=100)
	status = models.CharField(max_length=7, default='unmatched', editable=True)


class GroupB(models.Model):
	organiser_name=models.CharField(max_length=100)
	name2=models.CharField(max_length=100)
	name3=models.CharField(max_length=100)
	name4=models.CharField(max_length=100)
	organiser_email=models.CharField(max_length=100)
	status = models.CharField(max_length=7, default='unmatched', editable=True)



class User(models.Model):
	user_name=models.CharField(max_length=100)


class GroupOfEight(models.Model):
	organiser_name_a=models.CharField(max_length=100)
	organiser_name_b=models.CharField(max_length=100)
	organiser_email_a=models.CharField(max_length=100)
	organiser_email_b=models.CharField(max_length=100)

FND/shabbat/views.py
from django.shortcuts import render

from django.core.mail import send_mail
from .models import GroupA, GroupB , GroupOfEight
import dateutil

import datetime
import datetime as DT

import dateutil.relativedelta as REL

today = DT.date.today()
rd = REL.relativedelta(days=1, weekday=REL.FR)
next_friday = today + rd



# Create your views here.
def index(request):
	if request.method=="POST":
		organiser_name=request.POST['organiser_name']
		organiser_email=request.POST['organiser_email']
		name2=request.POST['name2']
		name3=request.POST['name3']
		name4=request.POST['name4']
		group_name=request.POST['group_name']

		'''small peice of code to get out the next friday in a variable..
		'''
		# send_mail('You have been matched!','You have been matched for dinenr on {}'.format(next_friday) ,
		# 'ozkilimportraits@gmail.com',[organiser_email], fail_silently=False)
		context = {'name':organiser_name , 'date':next_friday}
		group_a = GroupA(name2=name2,name3=name3,name4=name4, organiser_email=organiser_email)
		group_a.save()

		trial = GroupA.objects.filter(status='unmatched')[0]
		trial.status='matched'
		trial.save()

		'''this gets the first unmatched value--- the thing is that you get put into a waiting line.... how to deal with this'''
		
		group_b_unmatched = GroupB.objects.filter(status='unmatched')[0]
		group_b_unmatched.status='matched'
		group_b_unmatched.save()

		# GroupOfEight(organiser_name_a= organiser_name, organiser_name_b=, organiser_email_a=organiser_email, organiser_email_b=)
		return render(request,"thankyou.html" , context)
	else:
		return render(request, "front.html")


def index_hebrew(request):
	if request.method=="POST":
		organiser_name=request.POST['organiser_name']
		organiser_email=request.POST['organiser_email']
		name2=request.POST['name2']
		name3=request.POST['name3']
		name4=request.POST['name4']
		group_name=request.POST['group_name']

		'''small peice of code to get out the next friday in a variable..
		'''
		import datetime as DT
		import dateutil.relativedelta as REL
		today = DT.date.today()
		rd = REL.relativedelta(days=1, weekday=REL.FR)
		next_friday = today + rd
		
		# send_mail('You have been matched!','You have been matched for dinenr on {}'.format(next_friday) ,
		# 'ozkilimportraits@gmail.com',[organiser_email], fail_silently=False)
		context = {'name':organiser_name , 'date':next_friday}

		group_b = GroupB(name2=name2,name3=name3,name4=name4, organiser_email=organiser_email)
		group_b.save()


		trial = GroupA.objects.filter(status='unmatched')[0]
		trial.status='matched'
		trial.save()

		'''this gets the first unmatched value--- the thing is that you get put into a waiting line.... how to deal with this'''
		
		group_b_unmatched = GroupB.objects.filter(status='unmatched')[0]
		group_b_unmatched.status='matched'
		group_b_unmatched.save()

		return render(request,"thankyou.html" , context)
	else:
		return render(request, "front.html")


def matcher():

	"""this fucntion matches a group b for the group a 
	that had signedin and renders a page that gives their details and 
	sends an email automatically with the details of group b 
	then blocks you out of the front page ?
	find how to send automatic email with the 
	data from gmail account to email inputted?..
	"""
# 	group_a=GroupA()
# 	are_they_matched = GroupA.objects.all()
# 	print(are_they_matched)

# matcher()

# https://codemyui.com/button-to-email-subscription-field/
# use this! its very cool ui

def hello(request):
	return render(request, "trialfrontend.html")

FND/shabbat/templates/front.html
<!doctype html>
<html lang="en">

    <head>

    

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">






    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="file:///Users/ozkilim/Downloads/bootstrap%20(2).css" rel="stylesheet.css" type='text/css'>


  </head>
<body>
    <div class="container">
   <div class="row">
<div class="col-2">
   </div>
 <div class="col-8">

    <img src="{% static 'images/signupenglish.png'%}" class="signuplogo">

      <form method="POST">{% csrf_token %}

      <input type="text" class="form-control" name="organiser_name" placeholder="Organser name">
      <input type="text" class="form-control" name="organiser_email" placeholder="Organiser email"><br>
      <input type="text" class="form-control" name="name2" placeholder="Name 2">
      <input type="text" class="form-control" name="name3" placeholder="Name 3">
      <input type="text" class="form-control"  name="name4" placeholder="Name 4">
      <input type="text" class="form-control" name="group_name" placeholder="Group name"><br>
    
  <button type="submit" role="button">Find a friday night dinner!</button>

</form>
 </div>

 <div class="col-2">
   </div>


</div>
    </div>
  </body>
</html>

FND/shabbat/templates/thankyou.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  	<div class="container">
    <h1> {{name}} You will have a group to have dinner on {{date}}</h1>
</div>

    <div class="container">

    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Step1</h1>
    <p class="lead">Contact your your group on ... they live in ... area You will recieve an email with teir contacts when the match is made</p>
  </div>
</div>

    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Step 2</h1>
    <p class="lead">Decide who is bringing what for shabbat night dinner</p>
  </div>
</div>

    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Step 3</h1>
    <p class="lead">Enjoy and send your experiances or picutres to our facebook page her-->  </p>
  </div>
</div>
</div>


  </body>
</html>

FND/shabbat/templates/trialfrontend.html
<!DOCTYPE html>
<html>
<head>

{% load staticfiles %} 
<script src="/static/js/script.js"></script>
	
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<title></title>
</head>
<body>
<div class="container">

    <img src="{% static 'images/logo.png'%}" class="logo">
    <img src="{% static 'images/howitworks.png'%}">

    <a href="{% url 'shabbat:index' %}" class="signupbutton">Sign up!</a>


    </div>
</body>
</html>

FND/shabbat/templates/waiting.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  	<div class="container">
    <h1> {{name}} You have a group to have dinner with on {{date}}</h1>
</div>

    <div class="container">

    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">We are waiting to match you with a group!</h1>
    <p class="lead">You will recieve an email when you are matched with information about the group!</p>
  </div>
</div>
</div>

  </body>
</html>